import { SignIn, SignInButton, SignOutButton, SignedOut, useUser } from "@clerk/nextjs";
import Head from "next/head";

import { api } from "~/utils/api";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC! 🚀" })

  const user = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">

        <div>
          {/* // USER IS SIGNED IN */}
          {!user.isSignedIn && <SignInButton>
              <button style={{ color: 'skyblue' }}>Sign in with Clerk</button>
            </SignInButton> }
          
          {/* // USER IS SIGNED OUT */}
          {!!user.isSignedIn && <SignOutButton>
              <button style={{ color: 'skyblue' }}>Sign out with Clerk</button>
            </SignOutButton> }

          {/* <SignInButton>
              <button style={{ color: 'skyblue' }}>Sign in with Clerk</button>
            </SignInButton> */}
          {/* <h1 style={{ color: 'white' }}> SIGN OUT </h1>
            <SignOutButton>
              <button style={{ color: 'skyblue' }}>Sign out with Clerk</button>
            </SignOutButton> */}
        </div>
        <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
        <p className="text-2xl text-white">
          {hello.data ? hello.data.greeting : "Loading tRPC query..."}
        </p>

      </main>
    </>
  );
}
